cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartDetailView.as_view(), name='cart'),
    path('add/<int:product_id>', views.AddItemToCartView.as_view(), name="add_to_cart"),
    path('remove/<int:pk>', views.RemoveCartItemView.as_view(), name="remove_from_cart"),
    path('decrement/<int:pk>', views.DecrementCartItemQuantityView.as_view(), name="decrement_quantity"),
    path('increment/<int:pk>', views.IncrementCartItemQuantityView.as_view(), name="increment_quantity"),
]

checkout/urls.py
from django.urls import path

from checkout import views

app_name = 'checkout'

urlpatterns = [
    path("address/", views.CheckoutShippingDetailsSelectView.as_view(), name="address"),
    path("address/create/", views.CheckoutShippingDetailsCreateView.as_view(), name="address_create"),
    path("payment/", views.CheckoutPaymentDetailsSelectView.as_view(), name="payment"),
    path("payment/create", views.CheckoutPaymentDetailsCreateView.as_view(), name="payment_create"),
    path('confirmation/', views.OrderConfirmationView.as_view(), name="order_confirmation")
]

ecommerce_platform/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from . import views
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('', views.IndexView.as_view(), name="index"),
    path('products/', include("products.urls")),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('cart/', include("cart.urls")),
    path('checkout/', include("checkout.urls")),
]

# Serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path("", views.ProductListView.as_view(), name="product_list"),
    path("<int:pk>", views.ProductDetailView.as_view(), name="product_detail"),
    path("brands/", views.BrandsListView.as_view(), name="brands_list"),
]

cart/models.py
from django.conf import settings
from django.db import models

from products.models import Product


class Cart(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=False)

    def __str__(self):
        return f"{self.user}'s cart"

    def get_items(self):
        return self.cart_items.all().select_related('product')

    def get_total_price(self):
        return sum((item.product.price * item.quantity) for item in self.get_items())


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=False, related_name='cart_items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=False)
    quantity = models.PositiveIntegerField(default=1)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.item_name

    class Meta:
        ordering = ["-created"]

cart/forms.py
from django import forms


class AddItemToCartForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, initial=1, label=False)

cart/views.py
import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views import generic

from . import models, forms

logger = logging.getLogger('ecommerce-platform')


class CartDetailView(LoginRequiredMixin, generic.DetailView):
    model = models.Cart
    template_name = 'cart/cart_detail.html'

    def get_object(self, queryset=None):
        obj = models.Cart.objects.get(user=self.request.user)
        return obj

    def get_context_data(self, **kwargs):

        return super().get_context_data(**kwargs) | {
            "cart_items": self.object.get_items(),
            "total_items": self.object.get_items().count(),
            "total_price": self.object.get_total_price(),
            "cart_is_empty": self.object.get_items().count() == 0
        }


class AddItemToCartView(generic.View):
    model = models.CartItem

    def post(self, request, *args, **kwargs):
        form = forms.AddItemToCartForm(request.POST)

        if form.is_valid():
            product_id = self.kwargs.get('product_id')
            cart, _ = models.Cart.objects.get_or_create(user=self.request.user)
            quantity = form.cleaned_data['quantity']
            cart_item, created = models.CartItem.objects.get_or_create(product_id=product_id, cart=cart)

            if created:
                cart_item.quantity = quantity
            else:
                cart_item.quantity += quantity
            cart_item.save(update_fields=['quantity'])

        logger.info("Yay! Item added to cart")

        return redirect(reverse('cart:cart'))


class RemoveCartItemView(generic.DeleteView):
    model = models.CartItem
    success_url = reverse_lazy('cart:cart')

    def get_queryset(self):
        # not strictly needed for functionality but good to do for security purposes
        return models.CartItem.objects.filter(cart__user=self.request.user)


class DecrementCartItemQuantityView(generic.View):
    model = models.CartItem

    def post(self, request, *args, **kwargs):
        cart_item = models.CartItem.objects.get(pk=self.kwargs.get('pk'))

        if cart_item.quantity == 1:
            cart_item.quantity = 0
            cart_item.delete()
        else:
            cart_item.quantity -= 1
            cart_item.save(update_fields=['quantity'])

        return redirect(reverse('cart:cart'))


class IncrementCartItemQuantityView(generic.View):
    modes = models.CartItem

    def post(self, request, *args, **kwargs):
        cart_item = models.CartItem.objects.get(pk=self.kwargs.get('pk'))

        cart_item.quantity += 1
        cart_item.save(update_fields=['quantity'])

        return redirect(reverse('cart:cart'))

cart/templates/cart/cart_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h1 class="text-4xl mb-14">Your bag ({{ total_items }} item{{ total_items|pluralize }})</h1>
    {% if cart_is_empty %}
        <p>Your cart is empty</p>
    {% else %}
        <div style="display:grid; grid-template-columns: minmax(min-content, 350px) repeat(3, max-content); gap:20px; align-items: center">
            <p class="font-semibold">Item</p>
            <p class="font-semibold">Price</p>
            <p class="font-semibold mx-auto">Quantity</p>
            <div class="invisible">empty div</div>
            {% for item in cart_items %}
                <p>{{ item }}</p>
                <p>{{ item.product.price }} €</p>
                <div class="flex">
                    <form action="{% url 'cart:decrement_quantity' item.id %}" method="POST">
                        {% csrf_token %}
                        <button class="px-3 py-1 hover:bg-gray-100">-</button>
                    </form>
                    <p class="mx-auto px-2 py-1">{{ item.quantity }}</p>
                    <form action="{% url 'cart:increment_quantity' item.id %}" method="POST">
                        {% csrf_token %}
                        <button class="px-3 py-1 hover:bg-gray-100">+</button>
                    </form>
                </div>
                <form action="{% url 'cart:remove_from_cart' item.id %}" method="POST" class="mx-auto my-auto">
                    {% csrf_token %}
                    <button class="flex px-3 py-1 hover:bg-gray-100">
                        <img src="{% static 'svgs/trash.svg' %}" alt="" class="align-center" style="height: 20px;">
                    </button>
                </form>
            {% endfor %}
            <p class="font-semibold">Total:</p>
            <p class="font-semibold">{{ total_price }} €</p>
        </div>
        <div class="flex gap-x-8 mt-12 items-center">
            <a href="{% url 'products:product_list' %}" class="button-secondary">Continue shopping</a>
            <a href="{% url 'checkout:address' %}" class="button">Go to checkout</a>
        </div>
    {% endif %}
{% endblock %}