cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartDetailView.as_view(), name='cart'),
    path('add/<int:product_id>', views.AddItemToCartView.as_view(), name="add_to_cart"),
    path('remove/<int:pk>', views.RemoveCartItemView.as_view(), name="remove_from_cart"),
    path('decrement/<int:pk>', views.DecrementCartItemQuantityView.as_view(), name="decrement_quantity"),
    path('increment/<int:pk>', views.IncrementCartItemQuantityView.as_view(), name="increment_quantity"),
]

ecommerce_platform/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from . import views
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('', views.IndexView.as_view(), name="index"),
    path('products/', include("products.urls")),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('cart/', include("cart.urls")),
    path('checkout/', include("checkout.urls")),
]

# Serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path("", views.ProductListView.as_view(), name="product_list"),
    path("<int:pk>", views.ProductDetailView.as_view(), name="product_detail"),
    path("brands/", views.BrandsListView.as_view(), name="brands_list"),
]

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Gabylando</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="shortcut icon" type="image" href="{% static "svgs/favicon.svg" %}">
</head>
<body>
{% block navbar %}
    <div class="flex items-center justify-between pb-6">
        <a href="{% url "index" %}">
            <img src="{% static 'svgs/logo.svg' %}" alt="" width="160" height="35">
        </a>
        <div class="flex gap-10">
            <a href="{% url 'products:product_list' %}" class="link">All products</a>
            <a href="{% url 'products:brands_list' %}" class="link">Brands</a>
            <a href="#" class="link">Categories</a>
            <a href="#" class="link">Deals</a>
        </div>
        <div class="flex gap-10">
            {% if user.is_authenticated %}
                <form action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <button class="nav-link" type="submit">Log out</button>
                </form>
            {% else %}
                <a href="{% url 'login' %}" class="link">Log in</a>
            {% endif %}
            <a href="{% url 'cart:cart' %}" class="link">Cart</a>
        </div>
    </div>
{% endblock %}
<div style="max-width:1200px; margin: 70px auto">
    {% block content %}
    {% endblock content %}
</div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% if user.is_authenticated %}
        <div>Hello {{ user.username }}, you are now logged in!</div>
    {% else %}
        <div>You are now logged out</div>
    {% endif %}
{% endblock %}