cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartDetailView.as_view(), name='cart'),
    path('add/<int:product_id>', views.AddItemToCartView.as_view(), name="add_to_cart"),
    path('remove/<int:pk>', views.RemoveCartItemView.as_view(), name="remove_from_cart"),
    path('decrement/<int:pk>', views.DecrementCartItemQuantityView.as_view(), name="decrement_quantity"),
    path('increment/<int:pk>', views.IncrementCartItemQuantityView.as_view(), name="increment_quantity"),
]

ecommerce_platform/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from . import views
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('', views.IndexView.as_view(), name="index"),
    path('products/', include("products.urls")),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('cart/', include("cart.urls")),
    path('checkout/', include("checkout.urls")),
]

# Serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path("", views.ProductListView.as_view(), name="product_list"),
    path("<int:pk>", views.ProductDetailView.as_view(), name="product_detail"),
    path("brands/", views.BrandsListView.as_view(), name="brands_list"),
]

products/models.py
from django.core.validators import MinValueValidator
from django.db import models
from datetime import date

from django.db.models import CheckConstraint, Q
from core.models import StatusMixin

PRODUCT_CATEGORIES = {
    "SHOES": "Shoes",
    "CLOTHING": "Clothing",
    "ACCESSORIES": "Accessories"
}


class Product (StatusMixin, models.Model):
    category = models.CharField(max_length=50, choices=PRODUCT_CATEGORIES)
    brand = models.CharField(max_length=50)
    item_name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=5, decimal_places=2, validators=[MinValueValidator(0.0)])
    date_created = models.DateField(default=date.today)

    def __str__(self):
        return self.item_name

    class Meta:
        constraints = [
            CheckConstraint(condition=Q(price__gte=0.01), name='positive_price')
        ]


class ProductImage(models.Model):
    product = models.ForeignKey("Product", on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to="images/")

products/views.py
from django.core.cache import cache
from django.views.generic import DetailView, ListView, TemplateView

from products.models import Product
from cart.forms import AddItemToCartForm


class ProductListView(ListView):
    model = Product
    template_name = 'products/product_list.html'
    context_object_name = "products"


class ProductDetailView(DetailView):
    model = Product
    template_name = 'products/product_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["images"] = self.object.images.all()
        context['cart_form'] = AddItemToCartForm()
        return context


class BrandsListView(TemplateView):
    template_name = 'products/brands_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['brands'] = Product.objects.values_list('brand', flat=True).distinct().order_by('brand')
        return context

products/templates/products/brands_list.html
{% extends 'base.html' %}
{% block content %}
    {% for brand in brands %}
        <div>
            {{ brand }}
        </div>
    {% endfor %}
{% endblock %}

products/templates/products/index.html
{% extends 'products/base.html' %}
{% block content %}
    <h1>Gaby's e-commerce platform</h1>
    <p>Click <a href="{% url 'product_list' %}">here</a> to see all products!</p>
{% endblock %}

products/templates/products/product_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="grid grid-cols-2">
        <div class="mx-auto">
            {% if images %}
                {% for obj in images %}
                    <img src="{{ obj.image.url }}" alt="" style="width: 400px">
                {% endfor %}
            {% endif %}
        </div>
        <div class="flex flex-col gap-y-2 ml-5">
            <div>
                <p class="capitalize text-xl">{{ product.brand }}</p>
                <p class="capitalize text-3xl font-semibold">{{ product.item_name }}</p>
                <p class="text-xl">{{ product.price }} €</p>
            </div>
            <div class="mt-12">
                {% if user.is_authenticated %}
                    <form action="{% url "cart:add_to_cart" product.id %}" method="POST" class="flex gap-x-4">
                        {% csrf_token %}
                        {{ cart_form }}
                        <button type="submit" class="button">Add to cart</button>
                    </form>
                {% else %}
                    <div class="flex gap-x-4">
                        <div class="self-center">
                            {{ cart_form }}
                        </div>
                        <a href="{% url 'login' %}?next={{ request.get_full_path }}" class="button block">Add to
                            cart</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

products/templates/products/product_list.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="text-4xl pb-5">All products</h1>
    <div class="grid grid-cols-4 gap-x-5 gap-y-12">
        {% for product in products %}
                <a href="{% url 'products:product_detail' product.pk %}" class="flex flex-col mx-auto">
                    {% if product.images %}
                        <img src="{{ product.images.first.image.url }}" alt="" class="mx-auto" style="height:300px">
                    {% endif %}
                    <div class="flex gap-x-2 justify-between pt-2">
                        <p>{{ product.item_name }}</p>
                        <p>{{ product.price }} €</p>
                    </div>
                </a>
        {% endfor %}
    </div>
{% endblock %}